name: uda_dog
channels:
 - pytorch
 - conda-forge
dependencies:
 - numpy=1.16.4
 - matplotlib=3.1.0
 - tqdm=4.32.1
 - jupyter=1.0.0
 - pytorch
 - torchvision
 - cudatoolkit=10.2
 - pillow=6.1.0
 - pip=19.1.1
 - scikit-learn
 - pip:
   - opencv-python
